### PR TITLE
Feature/fix dynamics

### LINKED ISSUE #3: unstable PID parameters for Gazebo
Reference https://github.com/xArm-Developer/xarm_ros/commit/d956104f6cb51537db73218cbbbdfa7a51444939
**Summery**
The arm runs out of control when the PID gain is set in the Gazebo simulator. This problem needs to be solved.

If the PID gain is not set, the arm does not perform physical operations of force.
If it grabs an object, it grabs it with infinite force. If it hits a wall, it will bite into the wall and explode.

### PR DESCRIPTION
**Pull request by nyxrobotics**
Fix #3
- [ ] ~~Set "pi" macro~~ -> As a result, it was unnecessary. It was a mistake.
- [x] Fix joint position
- [x] Set implicitSpringDamping for damping joints
- [x] Fix maximum torque
- [x] Fix the range of motion
- [ ] ~~Update moveit config~~ -> It was not necessary.

### CODE REVIEW

**Comment by nyxrobotics** [comment]
@jsupratman13 Does this affect Moveit Config? If not, then the work is almost done.

**Comment by jsupratman13** [comment]
@nyxrobotics to a certain extent.
In terms of motion planning, collision, and joint range, the current MoveIt configuration should be ok.

If you want to consider the motion planning execution in Gazebo, you might want to adjust the execution tolerance (planning/execution will succeed visually but internally you might face execution timeout failure due to the arm unable to reach the target pose within tolerance level)

**Comment by nyxrobotics** [comment]
**For reviewers**

- Please enable/disable this PID gains.
https://github.com/sbgisen/xarm_ros/blob/15e90f9e403e0114f61c3c546bf46e461f189840/xarm_controller/config/xarm7_traj_controller.yaml#L70-L79

- Run below to test
```bash
roslaunch xarm_gazebo xarm7_beside_table.launch
```

- Desired Results
  - When PID option is enabled, reaction force is calculated when the arm hits a desk or other object and the arm does not penetrate the desk.
  - When PID option is disabled, the movement is smooth, but physics calculation is wrong when the arm collides with a desk.

- TODO(Will be fixed in another PR.)
  - Enabling PID option will shift the initial posture. I do not know the cause.
  - Enabling PID option slows down the joint velocity. The viscosity of the joint and PID gain must be adjusted.

**Comment by nyxrobotics** [comment]
To move the gripper joints in PID control mode, the following settings must be enabled.
https://github.com/sbgisen/xarm_ros/blob/15e90f9e403e0114f61c3c546bf46e461f189840/xarm_gripper/urdf/xarm_gripper.gazebo.xacro#L53-L79

Edit this file to adjust gain.
https://github.com/sbgisen/xarm_ros/blob/15e90f9e403e0114f61c3c546bf46e461f189840/xarm_controller/config/gripper_traj_controller.yaml#L23-L30

**Comment by nyxrobotics** [comment]
@jsupratman13 Please check it on Gazebo. (Please check https://github.com/sbgisen/xarm_ros/issues/3#issuecomment-1103905165)
@Tacha-S Please check it on the real robot. (This PR should not affect.)
If both work well, the later will merge this.

**Comment by jsupratman13** [comment]
> To move the gripper joints in PID control mode, the following settings must be enabled.
> 
> https://github.com/sbgisen/xarm_ros/blob/15e90f9e403e0114f61c3c546bf46e461f189840/xarm_gripper/urdf/xarm_gripper.gazebo.xacro#L53-L79
> 
> Edit this file to adjust gain.
> 
> https://github.com/sbgisen/xarm_ros/blob/15e90f9e403e0114f61c3c546bf46e461f189840/xarm_controller/config/gripper_traj_controller.yaml#L23-L30

@nyxrobotics 
I don't think you need to mention this one since this PR doesn't cover gripper model

**Comment by jsupratman13** [comment]
@nyxrobotics 

~~Just to confirm, I can't seem to control joint1, joint3, joint5, and joint7 on Gazebo with PID enabled. Is this due to the inappropriate PID gains or due to the new dynamics?~~

Seems like this problem persists in the previous commit so ignore for now.

**Review by jsupratman13 — APPROVED** [review]
Looks ok unless the joint1,3,5,7 should be controllable with PID enabled then please comment.

Waiting for the check on the real robot.

**Review by Tacha-S — APPROVED** [review]

**Pull request merged**
